name: Task 4 - 2 (Handle Deployment)
on: 
  push:
    branches: [main]
  workflow_dispatch:

defaults:
  run:
    working-directory: "./04PracticeProject(Start)"

jobs:
  w2:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
            path: ~/.npm
            key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: pwd
        run: pwd
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
