name: Task 4 - 1 (Handle Issues)
on: 
  issues:
  workflow_dispatch:

jobs:
  w1:
    runs-on: ubuntu-latest
 
    steps:
      - name: Output Event Details
        run: echo "${{toJSON(github.event)}}"
      