name: Task 4 - 2 (Handle Issues)
on: 
  push:
    branches: [main]
  workflow_dispatch:

defaults:
  run:
    working-directory: "./04 Practice Project (Start)"

jobs:
  w2:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Lint
        run: npm lint
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
